//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMS.EF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using REMS.EF.Context;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class REMSEntities : DbContext,IDbContext
    {
        public REMSEntities()
            : base("name=REMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Estate> Estates { get; set; }
        public virtual DbSet<Tenant> Tenants { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<House> Houses { get; set; }
    
        public virtual int Mark_Estate_And_RelatedData_AsDeleted(Nullable<long> inPutEstateId, string userId)
        {
            var inPutEstateIdParameter = inPutEstateId.HasValue ?
                new ObjectParameter("inPutEstateId", inPutEstateId) :
                new ObjectParameter("inPutEstateId", typeof(long));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Mark_Estate_And_RelatedData_AsDeleted", inPutEstateIdParameter, userIdParameter);
        }
    
        public virtual int Mark_House_And_Related_DataAs_Deleted(Nullable<long> inPutHouseId, string userId)
        {
            var inPutHouseIdParameter = inPutHouseId.HasValue ?
                new ObjectParameter("inPutHouseId", inPutHouseId) :
                new ObjectParameter("inPutHouseId", typeof(long));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Mark_House_And_Related_DataAs_Deleted", inPutHouseIdParameter, userIdParameter);
        }
    
        public virtual int Mark_Tenant_And_Related_DataAs_Deleted(Nullable<long> inPutTenantId, string userId)
        {
            var inPutTenantIdParameter = inPutTenantId.HasValue ?
                new ObjectParameter("inPutTenantId", inPutTenantId) :
                new ObjectParameter("inPutTenantId", typeof(long));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Mark_Tenant_And_Related_DataAs_Deleted", inPutTenantIdParameter, userIdParameter);
        }
    }
}
